package com.baitcheck.analyzers;

import com.baitcheck.analysis.Analyzer;
import com.baitcheck.analysis.Finding;
import com.baitcheck.model.Email;
import com.baitcheck.model.EmailAddress;
import com.baitcheck.model.Headers;
import com.baitcheck.util.Brand;
import com.baitcheck.util.DomainUtils;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public final class HeaderAnalyzer implements Analyzer {

    private static final String CAT = "Sender";
    private static final Pattern EMAIL_IN_TEXT = Pattern.compile("[\\w.+-]+@([\\w-]+\\.)+[a-zA-Z]{2,}");
    private static final Pattern MESSAGE_ID_DOMAIN = Pattern.compile("@([^>\\s]+)>?");
    private static final Pattern RECEIVED_FROM = Pattern.compile("(?i)^from\\s+(\\S+)(?:\\s+\\(([^)]*)\\))?");

    @Override
    public List<Finding> analyze(Email email) {
        List<Finding> out = new ArrayList<>();
        Headers h = email.headers();
        EmailAddress from = email.from();

        if (from.isEmpty() || from.domain().isEmpty()) {
            out.add(Finding.high(CAT, "Missing or malformed From address",
                    "From: " + h.first("From").orElse("(none)")));
            return out;
        }
        String fromDomain = from.domain();
        String fromReg = DomainUtils.registrableDomain(fromDomain);

        checkDisplayName(from, out);

        DomainUtils.findImpersonation(fromDomain).ifPresent(imp -> out.add(Finding.high(CAT,
                "Sender domain imitates " + imp.brand().name(), imp.reason())));

        h.first("Reply-To").map(EmailAddress::parse).filter(r -> !r.isEmpty()).ifPresent(replyTo -> {
            String replyReg = DomainUtils.registrableDomain(replyTo.domain());
            if (!replyReg.equals(fromReg)) {
                boolean freeMail = DomainUtils.FREE_MAIL.contains(replyReg);
                String detail = "From is @" + fromDomain + " but replies go to " + replyTo.address()
                        + (freeMail ? " (a free webmail account)" : "");
                out.add(freeMail
                        ? Finding.high(CAT, "Replies are redirected to a free email account", detail)
                        : Finding.medium(CAT, "Reply-To domain differs from sender", detail));
            }
        });

        h.first("Return-Path").map(EmailAddress::parse).filter(r -> !r.isEmpty()).ifPresent(rp -> {
            String rpReg = DomainUtils.registrableDomain(rp.domain());
            if (!rpReg.equals(fromReg)) {
                out.add(Finding.low(CAT, "Return-Path domain differs from sender",
                        "Bounces go to " + rp.address() + " while From is @" + fromDomain
                                + ". Common with mailing services, but also with spoofing."));
            }
        });

        String messageId = h.first("Message-ID").orElse("");
        if (messageId.isBlank()) {
            out.add(Finding.low(CAT, "No Message-ID header",
                    "Real mail servers almost always add one; scripts and spam kits often don't."));
        } else {
            Matcher m = MESSAGE_ID_DOMAIN.matcher(messageId);
            if (m.find()) {
                String idReg = DomainUtils.registrableDomain(m.group(1).toLowerCase(Locale.ROOT));
                if (!idReg.equals(fromReg)) {
                    out.add(Finding.low(CAT, "Message-ID was generated by a different domain",
                            "Message-ID domain is " + idReg + ", sender is " + fromReg));
                }
            }
        }

        if (!h.has("Date")) {
            out.add(Finding.low(CAT, "No Date header", "Legitimate mail clients always set a date."));
        }

        List<String> received = h.all("Received");
        if (!received.isEmpty()) {
            Matcher m = RECEIVED_FROM.matcher(received.get(received.size() - 1));
            String origin = m.find()
                    ? m.group(1) + (m.group(2) != null ? " (" + m.group(2) + ")" : "")
                    : received.get(received.size() - 1);
            out.add(Finding.info(CAT, "Passed through " + received.size() + " mail server(s)",
                    "Earliest hop: " + origin));
        }
        return out;
    }

    private void checkDisplayName(EmailAddress from, List<Finding> out) {
        String display = from.displayName().toLowerCase(Locale.ROOT);
        if (display.isBlank()) {
            return;
        }

        Matcher emailInName = EMAIL_IN_TEXT.matcher(from.displayName());
        if (emailInName.find() && !emailInName.group().equalsIgnoreCase(from.address())) {
            out.add(Finding.high(CAT, "Display name contains a different email address",
                    "Shows \"" + from.displayName() + "\" but actually sent from " + from.address()));
        }

        for (Brand brand : Brand.CATALOG) {
            for (String keyword : brand.keywords()) {
                if (Pattern.compile("\\b" + Pattern.quote(keyword) + "\\b").matcher(display).find()
                        && !brand.owns(from.domain())) {
                    out.add(Finding.high(CAT, "Display name claims to be " + brand.name(),
                            "\"" + from.displayName() + "\" but the address is " + from.address()
                                    + ", which " + brand.name() + " doesn't own"));
                    return;
                }
            }
        }
    }
}
